version: '3.7'

networks:
  my_network:
    external: true

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    networks:
      - my_network
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  flask_app:
    build: ./flask_app
    container_name: flask_app
    networks:
      - my_network
    depends_on:
      - mongodb
    ports:
      - 5000:5000

  nodered:
    build: ./nodered
    container_name: nodered
    networks:
      - my_network
    ports:
      - 1880:1880

volumes:
  mongo_data:
