version: '3.7'

networks:
  my_network:
    external: true

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    networks:
      - my_network
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data:

